### ISSUE TITLE
HashTable

### ISSUE THREAD

**Issue by jiwon2724** [eunjjungg/TIL#10]
## 질문
1. hash 함수란 무엇인지 설명해 주세요~
2. HashTable의 충돌 해결 방법을 설명해 주세요~

**Comment by eunjjungg** [comment]
1. hash 함수란 들어올 수 있는 모든 key 값에 대해 **고정된 길이의 문자열**로 변환하는 함수
2. chaining, open addressing이 있음. 체이닝은 한 버킷에 이미 데이터가 있다면 노드를 더 달아서 체이닝하는 방식임. 오픈 어드레싱은 key를 해시함수를 사용해 나온 인덱스 값이 아니어도 다른 인덱스에도 저장할 수 있음. 즉 결론적으로 충돌이 해결되는 것이 아니고 회피하는 방식임.
