### ISSUE TITLE
BFS, DFS

### ISSUE THREAD

**Issue by jiwon2724** [eunjjungg/TIL#11]
## 질문
1. BFS를 설명해주세요.
2. DFS를 구현하는 2가지 방법은!?

**Comment by eunjjungg** [comment]
1. BFS는 Breadth First Search라는 뜻으로 root node부터 시작해서 root 다음 레벨의 leaf node 전체 순회 -> 그 다음 레벨의 leaf node 전체 순회 -> ... -> 마지막 레벨의 leaf node 전체 순회하는 방식임. 
2. 깊이 우선 탐색은 stack을 사용하거나 재귀함수를 사용해 구현할 수 있음.

**Comment by jiwon2724** [comment]
1. 임의의 노드도 가능해요!
