### ISSUE TITLE
퀵 정렬

### ISSUE THREAD

**Issue by jiwon2724** [eunjjungg/TIL#4]
## 질문
1. 퀵 정렬에 대해서 설명해주세용

**Comment by eunjjungg** [comment]
Divide & Conquer를 사용하는 알고리즘으로 pivot 값을 정한 후 그 값보다 큰, 작은 값으로 배열을 구성하고 다시 앞에서 구한 작은, 큰 값에 대해 pivot을 각각 정한 후 또다시 정렬을 합니다. 반복하다 보면 정렬이 완료가 됩니다. 
time complexity는 worst case를 제외하면 O(nlogn)으로 worst는 O(n^2)입니다. worst가 발생하는 케이스는 피봇의 값이 최대값이거나 최소값일 때 발생합니다.
