### ISSUE TITLE
병합 정렬

### ISSUE THREAD

**Issue by jiwon2724** [eunjjungg/TIL#5]
## 질문
1. quick sort와 merge sort를 비교해서 설명해주세용

**Comment by eunjjungg** [comment]
둘 다 divide and conquer 방식을 사용한다는 점에서는 같지만 quick은 pivot을 정한 후 그 값을 기준으로 divide를 진행하지만 merge sort는 size가 1이 될 때까지 배열의 모든 값을 divide한다는 점이 다릅니다.
