### ISSUE TITLE
기수 정렬

### ISSUE THREAD

**Issue by jiwon2724** [eunjjungg/TIL#8]
## 질문
1. LSD와 MSD에 대해서 설명해주세용
2. 기수 정렬을 원소의 값을 비교할까요?

**Comment by eunjjungg** [comment]
1. least significant decimal, most significant decimal이라는 뜻으로 lsd는 마지막 자릿수부터, msd는 첫 번째 자릿수부터 기준을 잡는다는 의미입니다.
2. 아니요. 비교하지 않기 때문에 O(n)이 나옵니다.
